fix git utility commands

diff --git a/bin/git-is-clean b/bin/git-is-clean
--- a/bin/git-is-clean
+++ b/bin/git-is-clean
@@ -17,15 +17,14 @@ check() {
 
 errors=0
 git status --porcelain                              | check uncommitted files   || errors=$(( $errors + 1 ))
-git status | grep 'Your branch is ahead '           | check unpushed commits    || errors=$(( $errors + 1 ))
+git list-branches | grep -E '^ <?>|^. '             | check unpushed commits    || errors=$(( $errors + 1 ))
 git ls-files --other --directory | grep -v DS_Store | check ignored files       || errors=$(( $errors + 1 ))
-git branch | grep -v '^* master$'                   | check non-master branches || errors=$(( $errors + 1 ))
 git stash list                                      | check stashes             || errors=$(( $errors + 1 ))
 
 echo ------------------------------------------------------ >&2
 if [ "$errors" -eq 0 ]; then
-    printf '\033[30;1;42m  OK  \033[0m This repository is clean and safe to delete\n' >&2
+    printf '\033[42m  OK  \033[0m This repository is clean and safe to delete\n' >&2
 else
-    printf '\033[30;1;41m  NG  \033[0m This repository is dirty \033[33m(with %d failures)\033[0m\n' $errors >&2
+    printf '\033[41m  NG  \033[0m This repository is dirty \033[33m(with %d failures)\033[0m\n' $errors >&2
     exit 1
 fi
